// Template Source: BaseEntityCollectionWithReferencesPage.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.CloudCommunications;
import com.microsoft.graph.models.Call;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.requests.CallCollectionWithReferencesRequestBuilder;
import com.microsoft.graph.requests.CallCollectionWithReferencesPage;
import com.microsoft.graph.requests.CallCollectionResponse;
import com.microsoft.graph.models.Call;
import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import com.microsoft.graph.http.BaseCollectionPage;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Call Collection With References Page.
 */
public class CallCollectionWithReferencesPage extends BaseCollectionPage<Call, CallCollectionWithReferencesRequestBuilder> {

    /**
     * A collection page for Call
     *
     * @param response the serialized CallCollectionResponse from the service
     * @param builder  the request builder for the next collection page
     */
    public CallCollectionWithReferencesPage(@Nonnull final CallCollectionResponse response, @Nullable final CallCollectionWithReferencesRequestBuilder builder) {
        super(response.value, builder, response.additionalDataManager());
    }

    /**
     * Creates the collection page for Call
     *
     * @param pageContents       the contents of this page
     * @param nextRequestBuilder the request builder for the next page
     */
    public CallCollectionWithReferencesPage(@Nonnull final java.util.List<Call> pageContents, @Nullable final CallCollectionWithReferencesRequestBuilder nextRequestBuilder) {
        super(pageContents, nextRequestBuilder);
    }
}
