// Template Source: BaseEntityRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.Security;
import com.microsoft.graph.requests.AlertCollectionRequestBuilder;
import com.microsoft.graph.requests.AlertRequestBuilder;
import com.microsoft.graph.security.requests.AlertCollectionRequestBuilder;
import com.microsoft.graph.security.requests.AlertRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequestBuilder;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Security Request Builder.
 */
public class SecurityRequestBuilder extends BaseRequestBuilder<Security> {

    /**
     * The request builder for the Security
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public SecurityRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the request
     *
     * @param requestOptions the options for this request
     * @return the SecurityRequest instance
     */
    @Nonnull
    public SecurityRequest buildRequest(@Nullable final com.microsoft.graph.options.Option... requestOptions) {
        return buildRequest(getOptions(requestOptions));
    }

    /**
     * Creates the request with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for this request
     * @return the SecurityRequest instance
     */
    @Nonnull
    public SecurityRequest buildRequest(@Nonnull final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        return new com.microsoft.graph.requests.SecurityRequest(getRequestUrl(), getClient(), requestOptions);
    }


    /**
     *  Gets a request builder for the Alert collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public AlertCollectionRequestBuilder alerts() {
        return new AlertCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("alerts"), getClient(), null);
    }

    /**
     * Gets a request builder for the Alert item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public AlertRequestBuilder alerts(@Nonnull final String id) {
        return new AlertRequestBuilder(getRequestUrlWithAdditionalSegment("alerts") + "/" + id, getClient(), null);
    }
    /**
     *  Gets a request builder for the Alert collection
     *
     * @return the collection request builder
     */
    @Nonnull
    public AlertCollectionRequestBuilder alerts_v2() {
        return new AlertCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("alerts_v2"), getClient(), null);
    }

    /**
     * Gets a request builder for the Alert item
     *
     * @return the request builder
     * @param id the item identifier
     */
    @Nonnull
    public AlertRequestBuilder alerts_v2(@Nonnull final String id) {
        return new AlertRequestBuilder(getRequestUrlWithAdditionalSegment("alerts_v2") + "/" + id, getClient(), null);
    }
}
